version: '2'


services:

    second:
      image: nginx
      ports:
       - "80:80"
      volumes:
        - ./data/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./data/www/:/www/:ro

